CREATE TABLE patient (p_ID int(10) NOT NULL AUTO_INCREMENT, p_Name varchar(30) NOT NULL, p_Email varchar(30) UNIQUE, p_Age int(5) NOT NULL, p_phoneNo int(11) NOT NULL, password varchar(255) NOT NULL, PRIMARY KEY (p_ID));
CREATE TABLE Appoinment (Appoinment_no int(10) NOT NULL, `DATE` varchar(20) NOT NULL, Time varchar(10), patientp_ID int(10) NOT NULL, PRIMARY KEY (Appoinment_no, `DATE`));
CREATE TABLE Doctor (D_id int(10) NOT NULL AUTO_INCREMENT, D_Name varchar(30) NOT NULL, D_email varchar(30) NOT NULL UNIQUE, D_phoneNo int(10) NOT NULL, password varchar(255), patientp_ID int(10) NOT NULL, PRIMARY KEY (D_id));
CREATE TABLE Treatment_Chart (T_id int(10) NOT NULL AUTO_INCREMENT, T_name varchar(30) NOT NULL, Cost int(10) NOT NULL, PRIMARY KEY (T_id));
CREATE TABLE Medicine (M_ID int(10) NOT NULL AUTO_INCREMENT, M_name varchar(20) NOT NULL UNIQUE, M_Quantity int(10), M_price int(10), patientp_ID int(10) NOT NULL, PRIMARY KEY (M_ID));
CREATE TABLE Offers (O_id int(10) NOT NULL AUTO_INCREMENT, O_name varchar(20) NOT NULL, Discount int(10), PRIMARY KEY (O_id));
CREATE TABLE Notificatios (N_id int(10) NOT NULL AUTO_INCREMENT, Message varchar(255), patientp_ID int(10) NOT NULL, AppoinmentAppoinment_no int(10) NOT NULL, AppoinmentDATE varchar(20) NOT NULL, PRIMARY KEY (N_id));
CREATE TABLE `Health Tips` (H_id int(10) NOT NULL AUTO_INCREMENT, tips varchar(255), DoctorD_id2 int(10) NOT NULL, PRIMARY KEY (H_id));
CREATE TABLE Treatment (Treatment_id int(10) NOT NULL AUTO_INCREMENT, Payment int(10) NOT NULL, AppoinmentAppoinment_no int(10) NOT NULL, AppoinmentDATE varchar(20) NOT NULL, Treatment_ChartT_id int(10) NOT NULL, OffersO_id int(10) NOT NULL, patientp_ID int(10) NOT NULL, PRIMARY KEY (Treatment_id));
CREATE TABLE Doctor_Treatment (DoctorD_id int(10) NOT NULL, TreatmentTreatment_id int(10) NOT NULL, PRIMARY KEY (DoctorD_id, TreatmentTreatment_id));
CREATE TABLE Medicine_Treatment (MedicineM_ID int(10) NOT NULL, TreatmentTreatment_id int(10) NOT NULL, PRIMARY KEY (MedicineM_ID, TreatmentTreatment_id));
CREATE TABLE Doctor_Medicine (DoctorD_id int(10) NOT NULL, MedicineM_ID int(10) NOT NULL, PRIMARY KEY (DoctorD_id, MedicineM_ID));
ALTER TABLE Entity ADD INDEX FKEntity849215 (), ADD CONSTRAINT FKEntity849215 FOREIGN KEY () REFERENCES Entity ();
ALTER TABLE Appoinment ADD INDEX FKAppoinment517392 (patientp_ID), ADD CONSTRAINT FKAppoinment517392 FOREIGN KEY (patientp_ID) REFERENCES patient (p_ID);
ALTER TABLE Doctor ADD INDEX CheckUp (patientp_ID), ADD CONSTRAINT CheckUp FOREIGN KEY (patientp_ID) REFERENCES patient (p_ID);
ALTER TABLE Medicine ADD INDEX FKMedicine584593 (patientp_ID), ADD CONSTRAINT FKMedicine584593 FOREIGN KEY (patientp_ID) REFERENCES patient (p_ID);
ALTER TABLE Notificatios ADD INDEX FKNotificati30880 (patientp_ID), ADD CONSTRAINT FKNotificati30880 FOREIGN KEY (patientp_ID) REFERENCES patient (p_ID);
ALTER TABLE Treatment ADD INDEX FKTreatment487883 (AppoinmentAppoinment_no, AppoinmentDATE), ADD CONSTRAINT FKTreatment487883 FOREIGN KEY (AppoinmentAppoinment_no, AppoinmentDATE) REFERENCES Appoinment (Appoinment_no, `DATE`);
ALTER TABLE Doctor_Treatment ADD INDEX FKDoctor_Tre243089 (DoctorD_id), ADD CONSTRAINT FKDoctor_Tre243089 FOREIGN KEY (DoctorD_id) REFERENCES Doctor (D_id);
ALTER TABLE Doctor_Treatment ADD INDEX FKDoctor_Tre479505 (TreatmentTreatment_id), ADD CONSTRAINT FKDoctor_Tre479505 FOREIGN KEY (TreatmentTreatment_id) REFERENCES Treatment (Treatment_id);
ALTER TABLE Treatment ADD INDEX FKTreatment457605 (Treatment_ChartT_id), ADD CONSTRAINT FKTreatment457605 FOREIGN KEY (Treatment_ChartT_id) REFERENCES Treatment_Chart (T_id);
ALTER TABLE Treatment ADD INDEX FKTreatment318247 (OffersO_id), ADD CONSTRAINT FKTreatment318247 FOREIGN KEY (OffersO_id) REFERENCES Offers (O_id);
ALTER TABLE Treatment ADD INDEX FKTreatment104261 (patientp_ID), ADD CONSTRAINT FKTreatment104261 FOREIGN KEY (patientp_ID) REFERENCES patient (p_ID);
ALTER TABLE Notificatios ADD INDEX FKNotificati561264 (AppoinmentAppoinment_no, AppoinmentDATE), ADD CONSTRAINT FKNotificati561264 FOREIGN KEY (AppoinmentAppoinment_no, AppoinmentDATE) REFERENCES Appoinment (Appoinment_no, `DATE`);
ALTER TABLE Medicine_Treatment ADD INDEX FKMedicine_T618044 (MedicineM_ID), ADD CONSTRAINT FKMedicine_T618044 FOREIGN KEY (MedicineM_ID) REFERENCES Medicine (M_ID);
ALTER TABLE Medicine_Treatment ADD INDEX FKMedicine_T930 (TreatmentTreatment_id), ADD CONSTRAINT FKMedicine_T930 FOREIGN KEY (TreatmentTreatment_id) REFERENCES Treatment (Treatment_id);
ALTER TABLE Doctor_Medicine ADD INDEX FKDoctor_Med729398 (MedicineM_ID), ADD CONSTRAINT FKDoctor_Med729398 FOREIGN KEY (MedicineM_ID) REFERENCES Medicine (M_ID);
ALTER TABLE Doctor_Medicine ADD INDEX FKDoctor_Med584789 (DoctorD_id), ADD CONSTRAINT FKDoctor_Med584789 FOREIGN KEY (DoctorD_id) REFERENCES Doctor (D_id);
ALTER TABLE `Health Tips` ADD INDEX `FKHealth Tip111158` (DoctorD_id2), ADD CONSTRAINT `FKHealth Tip111158` FOREIGN KEY (DoctorD_id2) REFERENCES Doctor (D_id);
